version: "3.9"
services:
  api:
    build: backend
    image: api:v1
    container_name: api
    command: >
      poetry run bash -c "cd src && poe row-migrate && python main.py"
    networks:
      - backend
    ports:
      - '8080:8080'
    env_file:
      - backend/.env/dev/.app.env
    volumes:
      - ./backend/htmlcov:/service/htmlcov
      - ./backend/src:/service/src
      - ./backend/tests:/service/tests
      - ./backend/migrations:/service/migrations
    restart: unless-stopped
    depends_on:
      - db

  db:
    build: backend/conf/postgres
    image: emurze/postgres:16
    container_name: db
    networks:
      - backend
    ports:
      - '5432:5432'
    env_file:
      - backend/.env/dev/.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin4:
    image: dpage/pgadmin4:8.1
    container_name: pgadmin4
    networks:
      - backend
    ports:
      - '8888:80'
    env_file:
      - backend/.env/dev/.pgadmin.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - db

  cache:
    image: 'redis:7'
    container_name: 'cache'
    command: redis-server /etc/redis.conf
    networks:
      - backend
    volumes:
      - cache_data:/data
      - ./backend/conf/cache:/etc/redis.conf
    restart: unless-stopped

  pubsub:
    image: 'redis:7'
    container_name: 'pubsub'
    command: redis-server /etc/redis.conf
    networks:
      - backend
    volumes:
      - pubsub_data:/data
      - ./backend/conf/pubsub:/etc/redis.conf
    restart: unless-stopped

volumes:
  cache_data:
  pubsub_data:
  pgadmin_data:
  postgres_data:

networks:
  backend: