"""empty message

Revision ID: 8f6007dbba3b
Revises: f5b6040e0a6e
Create Date: 2024-03-05 04:08:50.301343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f6007dbba3b"
down_revision: Union[str, None] = "f5b6040e0a6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "client",
        "username",
        existing_type=sa.VARCHAR(length=3),
        type_=sa.String(length=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "client",
        "username",
        existing_type=sa.String(length=256),
        type_=sa.VARCHAR(length=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
