"""empty message

Revision ID: e652f02b3ae2
Revises: 
Create Date: 2024-03-02 12:17:01.279538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e652f02b3ae2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column(
            "date_joined",
            sa.TIMESTAMP(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=True,
        ),
        sa.Column("last_login", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("client")
    # ### end Alembic commands ###
