"""empty message

Revision ID: 81339dd61c77
Revises: 02876ccfba0e
Create Date: 2024-04-07 17:52:34.088340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81339dd61c77"
down_revision: Union[str, None] = "02876ccfba0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "order", sa.Column("customer_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "order", "customer", ["customer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order", type_="foreignkey")
    op.drop_column("order", "customer_id")
    op.drop_table("customer")
    # ### end Alembic commands ###
