"""empty message

Revision ID: 9f369978397e
Revises: b4f29b678ca3
Create Date: 2024-03-26 20:39:31.748340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f369978397e"
down_revision: Union[str, None] = "b4f29b678ca3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("post_publisher_id_fkey", "post", type_="foreignkey")
    op.drop_column("post", "publisher_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post",
        sa.Column(
            "publisher_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "post_publisher_id_fkey", "post", "publisher", ["publisher_id"], ["id"]
    )
    # ### end Alembic commands ###
