"""empty message

Revision ID: b4f29b678ca3
Revises: ff594bd0d569
Create Date: 2024-03-26 10:41:02.867424

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4f29b678ca3"
down_revision: Union[str, None] = "ff594bd0d569"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publisher",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column(
        "post", sa.Column("publisher_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "post", "publisher", ["publisher_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "post", type_="foreignkey")
    op.drop_column("post", "publisher_id")
    op.drop_table("publisher")
    # ### end Alembic commands ###
