"""empty message

Revision ID: bac184bb6c0a
Revises: aaf8458cfbbd
Create Date: 2024-04-02 17:56:06.148754

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bac184bb6c0a"
down_revision: Union[str, None] = "aaf8458cfbbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("post")
    op.drop_table("publisher")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publisher",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="publisher_pkey"),
        sa.UniqueConstraint("name", name="publisher_name_key"),
    )
    op.create_table(
        "post",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "title",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "content",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("draft", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="post_pkey"),
    )
    op.drop_table("account")
    # ### end Alembic commands ###
