"""empty message

Revision ID: b431e523cc77
Revises: 65fbec98d3c0
Create Date: 2024-03-09 08:54:43.572317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b431e523cc77"
down_revision: Union[str, None] = "65fbec98d3c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client", sa.Column("title", sa.String(length=256), nullable=False)
    )
    op.add_column(
        "client", sa.Column("content", sa.String(length=256), nullable=False)
    )
    op.add_column("client", sa.Column("draft", sa.Boolean(), nullable=True))
    op.drop_constraint("client_username_key", "client", type_="unique")
    op.drop_column("client", "username")
    op.drop_column("client", "date_joined")
    op.drop_column("client", "last_login")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column(
            "last_login",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "client",
        sa.Column(
            "date_joined",
            postgresql.TIMESTAMP(),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "client",
        sa.Column(
            "username",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_unique_constraint("client_username_key", "client", ["username"])
    op.drop_column("client", "draft")
    op.drop_column("client", "content")
    op.drop_column("client", "title")
    # ### end Alembic commands ###
